### ISSUE TITLE
Error when using RangeAtttribute on double properties

### ISSUE THREAD

**Issue by calebroseland** [NJsonSchema/NJsonSchema#233]
Hi, 

I seem to have found an issue with `RangeAttribute` on `double` properties. When I generate schema for a class that has a `double` paired with range validation, I seem to get this error. Occurs in 5.x versions, does not occur in 4.x.

```
// these do work
[Range(0, 999)]
public int WorksOne{ get; set; }
[Range(0, 999)]
public long WorksTwo{ get; set; }

//these don't work
[Range(0, 9999.99)]
public double FailsOne { get; set; }
[Range(0, double.MaxValue)]
public double FailsTwo{ get; set; }
```

```
Microsoft.CSharp.RuntimeBinder.RuntimeBinderException was unhandled by user code
  HResult=-2146233088
  Message=Cannot implicitly convert type 'double' to 'decimal?'. An explicit conversion exists (are you missing a cast?)
  Source=Anonymously Hosted DynamicMethods Assembly
  StackTrace:
       at CallSite.Target(Closure , CallSite , Object )
       at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
       at CallSite.Target(Closure , CallSite , Object )
       at NJsonSchema.Generation.JsonSchemaGenerator.ApplyPropertyAnnotations(JsonSchema4 jsonProperty, Type parentType, IList`1 attributes, JsonObjectTypeDescription propertyTypeDescription) in C:\projects\njsonschema\src\NJsonSchema\Generation\JsonSchemaGenerator.cs:line 537
       at NJsonSchema.Generation.JsonSchemaGenerator.LoadPropertyOrField(MemberInfo property, Type propertyType, Type parentType, JsonSchema4 parentSchema, ISchemaResolver schemaResolver, ISchemaDefinitionAppender schemaDefinitionAppender) in C:\projects\njsonschema\src\NJsonSchema\Generation\JsonSchemaGenerator.cs:line 469
       at NJsonSchema.Generation.JsonSchemaGenerator.GeneratePropertiesAndInheritance(Type type, JsonSchema4 schema, ISchemaResolver schemaResolver, ISchemaDefinitionAppender schemaDefinitionAppender) in C:\projects\njsonschema\src\NJsonSchema\Generation\JsonSchemaGenerator.cs:line 265
       at NJsonSchema.Generation.JsonSchemaGenerator.GenerateObject[TSchemaType](Type type, TSchemaType schema, ISchemaResolver schemaResolver, ISchemaDefinitionAppender schemaDefinitionAppender) in C:\projects\njsonschema\src\NJsonSchema\Generation\JsonSchemaGenerator.cs:line 240
       at NJsonSchema.Generation.JsonSchemaGenerator.Generate[TSchemaType](Type type, IEnumerable`1 parentAttributes, ISchemaResolver schemaResolver, ISchemaDefinitionAppender schemaDefinitionAppender) in C:\projects\njsonschema\src\NJsonSchema\Generation\JsonSchemaGenerator.cs:line 110
       at NJsonSchema.Generation.JsonSchemaGenerator.Generate(Type type, ISchemaResolver schemaResolver, ISchemaDefinitionAppender schemaDefinitionAppender) in C:\projects\njsonschema\src\NJsonSchema\Generation\JsonSchemaGenerator.cs:line 62
       at NJsonSchema.Generation.JsonSchemaGenerator.GenerateInheritance(Type type, JsonSchema4 schema, ISchemaResolver schemaResolver, ISchemaDefinitionAppender schemaDefinitionAppender) in C:\projects\njsonschema\src\NJsonSchema\Generation\JsonSchemaGenerator.cs:line 299
       at NJsonSchema.Generation.JsonSchemaGenerator.GeneratePropertiesAndInheritance(Type type, JsonSchema4 schema, ISchemaResolver schemaResolver, ISchemaDefinitionAppender schemaDefinitionAppender) in C:\projects\njsonschema\src\NJsonSchema\Generation\JsonSchemaGenerator.cs:line 270
       at NJsonSchema.Generation.JsonSchemaGenerator.GenerateObject[TSchemaType](Type type, TSchemaType schema, ISchemaResolver schemaResolver, ISchemaDefinitionAppender schemaDefinitionAppender) in C:\projects\njsonschema\src\NJsonSchema\Generation\JsonSchemaGenerator.cs:line 240
       at NJsonSchema.Generation.JsonSchemaGenerator.Generate[TSchemaType](Type type, IEnumerable`1 parentAttributes, ISchemaResolver schemaResolver, ISchemaDefinitionAppender schemaDefinitionAppender) in C:\projects\njsonschema\src\NJsonSchema\Generation\JsonSchemaGenerator.cs:line 110
       at NJsonSchema.Generation.JsonSchemaGenerator.Generate(Type type) in C:\projects\njsonschema\src\NJsonSchema\Generation\JsonSchemaGenerator.cs:line 51
       at NJsonSchema.JsonSchema4.FromType(Type type, JsonSchemaGeneratorSettings settings) in 
...Redacted...
       at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
       at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
       at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
       at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
  InnerException: 

```

Is there anything I can do about this? Is there a breaking change from 4.x to 5.x that I need to be aware of?

**Comment by rsuter** [comment]
It seems that this is a regression fault introduced with the change to decimals in the schema... (introduced for improved precision). Ill fix this tomorrow..

**Comment by calebroseland** [comment]
Many thanks! Great library.

**Comment by rsuter** [comment]
v5.8

**Comment by rsuter** [comment]
Please report if its working for you..

**Comment by calebroseland** [comment]
Yes, v5.8 is working. However using `double.MaxValue` this happens. `Unhandled Exception: System.OverflowException: Value was either too large or too small for a Decimal.` Understandably so, as decimal is smaller.

**Comment by rsuter** [comment]
How would we fix this?

**Comment by calebroseland** [comment]
Well, if the value of a `double` is greater than `decimal.MaxValue`, it could be silently (configurable?) use that instead of the value that is too large.

What was the reason in switching to `decimal`?

**Comment by rsuter** [comment]
Yes, this is a good idea...

We switched because we had rounding problems with multiple of attributes and decimals are more precise for "usual" numbers
